/*
 * temperatures.c
 *
 *  Created on: May 29, 2023
 *      Author: Jacob Petersen
 */

#include "adc.h"

const uint32_t ADCCHANNELS[11] = {-1, ADC_CHANNEL_1, ADC_CHANNEL_2, ADC_CHANNEL_3, ADC_CHANNEL_4, ADC_CHANNEL_5,
								   	  ADC_CHANNEL_6, ADC_CHANNEL_7, ADC_CHANNEL_8, ADC_CHANNEL_9, ADC_CHANNEL_10};

uint16_t TEMP_getWellTemperatureReading(uint8_t wellID) {

	uint16_t result;

	ADC_ChannelConfTypeDef adcConfig = {0};

	// Configure the ADC for the channel desired (well 1 = channel 1, etc)
	adcConfig.Channel = ADCCHANNELS[wellID];

	// these settings copied from autogenerated code
	adcConfig.Rank = ADC_REGULAR_RANK_1;
	adcConfig.SamplingTime = ADC_SAMPLETIME_640CYCLES_5;
	adcConfig.SingleDiff = ADC_SINGLE_ENDED;
	adcConfig.OffsetNumber = ADC_OFFSET_NONE;
	adcConfig.Offset = 0;

	// Configure the channel with these new settings
	HAL_ADC_ConfigChannel(&hadc1, &adcConfig);

	// Perform self-calibration
	HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED);

	// Start conversion
	HAL_ADC_Start(&hadc1);

	// Poll for conversion with 1ms timeout
	while (HAL_ADC_PollForConversion(&hadc1, 1) != HAL_OK) {}

	uint32_t adcValue = HAL_ADC_GetValue(&hadc1);
	HAL_ADC_Stop(&hadc1);

	result = adcValue & 0xFFF; // 12 bits, pad 0s

	return result;
}
